steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/aegis-gsc-2026/aegis/aegis-orchestrator",
        "-f",
        "services/orchestrator/Dockerfile",
        "."
      ]
images:
  - asia-south1-docker.pkg.dev/aegis-gsc-2026/aegis/aegis-orchestrator