steps:
- name: gcr.io/cloud-builders/docker
  args: ["build", "-f", "services/dispatch/Dockerfile", "-t", "asia-south1-docker.pkg.dev/aegis-gsc-2026/aegis/aegis-dispatch:latest", "."]
images: ["asia-south1-docker.pkg.dev/aegis-gsc-2026/aegis/aegis-dispatch:latest"]